# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 21:39
from __future__ import unicode_literals

import amplio.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('upon', models.IntegerField(choices=[(0, 'Comment on feedback'), (1, 'Comment on comment')])),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Not really sure'), (1, 'Suggestions for improving existing apps'), (2, 'Bugs that need to be eliminated rapidly'), (3, 'Glitches that need to be eliminated casually'), (4, 'Ideas for building new apps')], default=0)),
                ('to', models.IntegerField(choices=[(3, 'IMG developers and designers'), (1, 'IMG developers'), (2, 'IMG designers'), (4, 'IIT officials')], default=3)),
                ('category', models.IntegerField(choices=[(0, 'No specific category or miscellaneous'), (1, 'IIT Roorkee website'), (2, 'IMG website'), (3, 'New entrants'), (4, 'Channel-i'), (5, 'Notice board'), (6, 'Lectures and tutorials'), (7, 'Lost and found'), (8, 'Buy and sell'), (9, 'People search'), (10, 'Jukebox'), (11, 'Kriti'), (12, 'Yaadein'), (13, 'Projects portal'), (14, 'Internship portal'), (15, 'Placement portal'), (16, 'Student homepage'), (17, 'DC++ hub'), (18, 'Bunk-o-meter Android app'), (19, 'Notice board Android app'), (20, 'Forum'), (21, 'FAQ'), (22, 'Media management system'), (23, 'Forminator'), (24, 'Status')], default=0)),
                ('image', models.ImageField(blank=True, upload_to='feedback/')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('votes', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Reported'), (1, 'Under consideration'), (2, 'Under construction'), (3, 'Under testing'), (4, 'Completed')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password_hash', models.CharField(max_length=2047)),
                ('post', models.IntegerField(choices=[(0, 'Student'), (1, 'IMG developer'), (2, 'IMG designer'), (4, 'IIT official')], default=0)),
                ('image', models.ImageField(blank=True, upload_to=amplio.models.user_upload_image)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplio.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplio.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upon_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='amplio.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upon_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplio.Feedback'),
        ),
    ]
