# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, upload_to='amplio/feedback/'),
        ),
    ]
