# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplio', '0002_auto_20160627_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='patrons',
            field=models.ManyToManyField(related_name='patronized_feedback_set', to='amplio.User'),
        ),
    ]
