# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplio', '0003_feedback_patrons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='votes',
        ),
    ]
