# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:35
from __future__ import unicode_literals

import amplio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplio', '0004_remove_feedback_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upon',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, upload_to=amplio.models.feedback_upload_image),
        ),
    ]
