# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplio', '0006_auto_20160701_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_email_hash',
            field=models.CharField(default='idkidkidkidkidkidk', max_length=255),
            preserve_default=False,
        ),
    ]
