# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplio', '0007_user_name_email_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='by',
            new_name='author',
        ),
    ]
