# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplio', '0008_auto_20160702_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_comment_set', to='amplio.User'),
        ),
    ]
